### ISSUE TITLE
Where is it saving to?

### ISSUE THREAD

**Issue by MeeslBub** [GrimKriegor/TES3MP-forge#6]
I created a folder in my home directory called tes3mp, Then typed in sudo docker run --rm -it -v tes3mp:/build grimkriegor/tes3mp-forge
Everything goes well, but the actual package is missing... Where is it saving to?
I'm running Mint uma

**Comment by GrimKriegor** [comment]
Hello there.

Package should be under `/build` on the container, so directly where you mount it on your host.

```
build
code
dependencies
keepers
build.log
tes3mp-server-GNU+Linux-x86_64-release-0.8.0-abdaedd752-ee0cb211b7.tar.gz
tes3mp-server.sh
```

However, this ` -v tes3mp:/build` might not be what you want, try it with ` -v $HOME/tes3mp-forge:/build` instead, so you can more easily locate the volume.
